[build]
  publish = "dist/public"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Redirect contact API to Netlify function
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

# Redirect AI chat API to Netlify function
[[redirects]]
  from = "/api/ai-chat"
  to = "/.netlify/functions/ai-chat"
  status = 200

# Test contact function for debugging
[[redirects]]
  from = "/api/test-contact"
  to = "/.netlify/functions/test-contact"
  status = 200

# Redirect other API calls to the proxy function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy/:splat"
  status = 200

# SPA routing - redirect all other routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 